#!/usr/bin/python
import subprocess
import sys

#List of Replica servers

replica_servers=[
"ec2-52-90-80-45.compute-1.amazonaws.com",
"ec2-54-183-23-203.us-west-1.compute.amazonaws.com",
"ec2-54-70-111-57.us-west-2.compute.amazonaws.com",
"ec2-52-215-87-82.eu-west-1.compute.amazonaws.com",
"ec2-52-28-249-79.eu-central-1.compute.amazonaws.com",
"ec2-54-169-10-54.ap-southeast-1.compute.amazonaws.com",
"ec2-52-62-198-57.ap-southeast-2.compute.amazonaws.com",
"ec2-52-192-64-163.ap-northeast-1.compute.amazonaws.com",
"ec2-54-233-152-60.sa-east-1.compute.amazonaws.com"]

#DNS Server location
dns_server="cs5700cdnproject.ccs.neu.edu"


#Checking and validating command line arguments

def command_args():

	global port
	global origin
	global name
	global username
	global keyfile

	if len(sys.argv) != 11:
		print "Error: Improper number of arguments"
		sys.exit()

	elif sys.argv[1] != '-p' or sys.argv[3] != '-o' or sys.argv[5] != '-n' or sys.argv[7] != '-u' or sys.argv[9] != '-i':
		print "Error: Improper format of arguments"
		sys.exit()

	if int(sys.argv[2]) not in range(40000, 65536):
		print "Error: Use port numbers between 40000 to 65535"
		sys.exit()
	else:
		port = sys.argv[2]

	origin = sys.argv[4]
	name = sys.argv[6]
	username = sys.argv[8]
	keyfile = sys.argv[10]

#stopping the http servers in every replica using pkill command
def stopCDN_http_servers():

	global replica_servers

	try:

	        for server in replica_servers:
			#Logging into the replicas and killing http server process
	        	testhttp = subprocess.check_output("ssh -i " + keyfile + " " + username + "@" + server + " 'pkill httpserver -u " + username + "'", shell=True)

		print "Stopped all httpservers(replicas)"

	except Exception as ex:
                        print "Exception Raised in Stopping Httpservers: " + str (ex)

#Stopping the dns server using pkill command
def stopCDN_dns_server():
	global dns_server

	try:
		#Logging into the dns server and killing dns server process
		deploydns = subprocess.check_output("ssh -i " + keyfile + " " + username + "@" + dns_server + " 'pkill dnsserver -u " + username + "'", shell=True)
		print "Stopped DNS server"
	except Exception as ex:
                        print "Exception Raised in Stopping DNSServer: " + str (ex)

#Start of execution
command_args()
stopCDN_http_servers()
stopCDN_dns_server()
